### ISSUE TITLE
.NET Standard 2.0 Support

### ISSUE THREAD

**Issue by aminzar-access** [Cimpress-MCP/serilog-sinks-awscloudwatch#130]
Hi,
Why are the new versions not supporting .NET Standard 2.0 anymore?

Cheers,
Amin

**Comment by wparad** [comment]
Because .Net Core has been dead for 4 years now, and since .NET 5 all released versions of the library work with all frameworks and operating systems.

The library currently targets the oldest available versions of .net core, and other platforms using the .net 6 target framework. (The one this library supports)

If the library does not work for your current deployment scenario, can you include which exact version of .NET core, or .NET you are running and a link to the Microsoft documentation that includes that that version has not been marked as obsolete and is still under support by Microsoft.

**Comment by wparad** [comment]
Closing due to lack of information.

**Comment by a-jackson** [comment]
@wparad we're using this with .Net Framework 4.8 which is still supported and has no end date https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

If you don't want to support it that's but .Net Standard 2.0 isn't legacy and unsupported.

**Comment by wparad** [comment]
@a-jackson this feels like a separate question. If the current version of the library doesn't work support .net4.8 and can easily be supported by adding that target to the list, we would gladly accept a PR for it.
