### ISSUE TITLE
Update reference of AWSSDK.Core to Latest Version

### ISSUE THREAD

**Issue by JoshuaRamirez** [Cimpress-MCP/serilog-sinks-awscloudwatch#138]
I'm using .NET AWS Lambda code in the same solution as code that uses Serilog - it's causing nuget version conflicts because my Lambda code uses a newer version of AWSSDK than Serilog. Obviously there is a work around, but it would be nice to have the updated version in place for ease of maintenance.

**Comment by wparad** [comment]
We obviously can't force the latest version on everyone, because (a) they might have their own requirements and (b) because we don't need it.

But that shouldn't cause an version conflicts because this library supports projects using the latest version already. Can you share exactly what the conflict looks like for you?

**Comment by williamhowf** [comment]
I agree that update AWSSDK.CloudWatchLogs version >= 3.7.106

**Comment by wparad** [comment]
What happens when you specify the version of the CW Logs package you want in your csproj?

**Comment by wparad** [comment]
Closing for now, as all dependencies can always be resolved when using this SerilogSinks library, as the library does not require a fixed version of any dependency. Make sure to always read the error message. In this case, the error message explicitly says to install `AWSSDK.Core` version `3.7.107.8`, doing so helps nuget to resolve the problem here.

Also for reference this includes more info: https://learn.microsoft.com/en-us/nuget/concepts/dependency-resolution

As a library, this CloudWatch SerilogSinks allows for any version greater than `3.5.1.7` of Core. If your nuget or dotnet executable is failing, please report the problem to the dotnet or nuget repositories, we can't fix it here.
