### ISSUE TITLE
Make log stream name configurable

### ISSUE THREAD

**Issue by aggieben** [Cimpress-MCP/serilog-sinks-awscloudwatch#23]
I'd like to customize my log stream names, rather than use the one generated.  In particular, `Dns.GetHostName()` would not be very useful for apps running on cloud VMs with names like `my-special-vm-us-west-1.aws.amazon.com` or whatever.  If I could customize the stream name, I'd have a bit better control over how things are organized in CloudWatch.

Thoughts?  I'm willing to contribute a PR for this, but thought some initial discussion was warranted before doing that.

**Comment by thoean** [comment]
```cs
var prefix = DateTime.UtcNow.ToString("yyyy-MM-dd-hh-mm-ss");
logStreamName = $"{prefix}_{Dns.GetHostName()}_{Guid.NewGuid()}";
```

It is sorted by creation time already, but yes, if you have long host names, it might be confusing. We're also using it when running in a cluster, so having some identification from where this stream originates makes often sense. But I can also imagine other use cases.

I'm mostly in favor in providing reasonable defaults with options to override. So adding a `Func<string> CreateLogStreamName {get;set;}` or even an `ILogStreamNameProvider LogStreamNameProvider {get; set;}` to `CloudWatchSinkOptions` makes sense. (I'm open to other suggestions of providing the override, but the options seem to be a reasonable point for configuring the sinks' behavior.)

**Comment by tmschlot** [comment]
+1 I'm in the same boat as @aggieben.  

@thoean, I would prefer your first suggestion -- `Func<string> CreateLogStreamName {get;set;}` -- over your second.  I don't see the need to create an entire class when a function will do.

**Comment by wparad** [comment]
@tmschlot, there are actually lots of reasons to create the class instead of using `Func` pattern.  The main use case is scalability.  Because this is a public library, using a string here, and then thinking later, "man, I wish I could have added a second parameter", requires creating a v2 in the code.  Starting with a class, makes this so much more clean.  The use of classes is much cleaner out of the box.

A secondary use case is testability.  Using a straight interface, allows the same mocking tools to continue to work.  Using a func, makes it less clean, and forces you to handle the testing cases that the mock (or spy) would have provided by default.

The last case is validation.  If you are a user of the library it may not be so obvious how to handle this, what types of return values are allowed.  Is any string, is null, is empty, etc...  What about side effects, how many times will this be called, will it be cached, etc...  With a class or interface, this can be defined and documented, the language support for that is better than documenting Func<>.

Technically these are the same (and to the CPU they are identical), but often the differences between philosophical changes make a world of difference to the teams that consume them.

**Comment by wparad** [comment]
@aggieben any followup here, or should we close this issue?

**Comment by aggieben** [comment]
Give me a week and I'll do my best to get something together.  If I haven't submitted something in a week we can close.

**Comment by thoean** [comment]
@aggieben , I assume you're not getting back to this. I'm closing this request, but we continue welcoming your contributions and discussions.
