### ISSUE TITLE
Add support for durable logging

### ISSUE THREAD

**Issue by zsims** [Cimpress-MCP/serilog-sinks-awscloudwatch#51]
Many of the other Serilog sinks support "durable" logging by the way of a buffer on disk. This would prevent the loss of logs on unexpected termination or Cloudwatch is down for prolonged period

Sinks that implement reliable logging (normally via the `RollingFileSink`):

 - https://github.com/serilog/serilog-sinks-elasticsearch
 - https://github.com/serilog/serilog-sinks-loggly

**Comment by thoean** [comment]
Thank you @zsims for the suggestions. This was one of the thoughts we had for the initial implementation, but then went for the easier implementation. One of the reasons was higher uptime expectation of CloudWatchLogs over external services (I'm not saying it's a fact in all cases and that CloudWatchLogs can never be down.)

Did you experience first hand downtime experience?

Would you be willing to come up with a pull request?

**Comment by zsims** [comment]
I haven't personally experienced failure to submit logs due to CloudWatch downtime. Although I have experienced the loss of logs with other sinks when not using durable logging in cases where upstream is down, or the process exits unexpectedly.

I'll look at raising a PR in my spare time, not sure when this may be though :-)

**Comment by zsims** [comment]
So I seen your point that not having this makes the sink much simpler. I've looked at the other sinks for inspiration, and what they have in common is:

 1. Sink state is pushed out to a common class, e.g. `CloudWatchLogSinkState`
 2. Introduce a new sink, e.g. `DurableCloudWatchLogSink`
 3. Use the rolling file sink for `DurableCloudWatchLogSink`, e.g on event as JSON per line
 4. Create a class to send logs from on disk. This would periodically scan for and read from the written files to send them from CloudWatchLogs

Keen for your thoughts around a suggested approach. Not sure how it would change the concept of custom renderers (as you can specify in the current sink options). Keeping the same batching behavior while being efficient will also be an interesting challenge.

As an aside, thanks for all your hard work in putting this sink together :)

**Comment by thoean** [comment]
I agree with your points. This can be achieved with good architecture. But this library would contain this additional complexity, from effectively two sinks to longer timing until the data are sent to CloudWatchLogs etc.

**Comment by wparad** [comment]
@zims, thanks for the suggestion and based on the discussion I am closing this.  I think there is a fundamental discrepancy of how you are using logs, if the durableness is of importance.  Since logging happens out of band, asynchronously, and by a separate mechanism, you should assume the logs that make it to CloudWatch is < 100%.  To make it be 100% you would want to fail the current process/retry the logging when it fails.  The reason is that only the main thread process can ensure the successful completion of an action/http request or return failure to the caller.  The Microsoft logging framework does not do that.

What you are suggesting seems like a different library.  Rather than implementing the suggestion, it would make more sense to use the Amazon CloudWatch sdk directly.  Even with a durable log writer, what if writing to the file fails, what if the process crashes, what if the hard drive runs out of space, etc... You can never handle all the problems, and instead you are swapping out the issues with HTTP/cloudwatch with ones about the file system.

I would argue, the purpose of the library is to ensure logs from the service get cloud watch.  With the assumption that the log sending process is faulty, we should improve the library to close down those bugs rather than wrapping the logging process with a file system write.  The library already handles a wide variety of possible log sending problems, and I believe the loss of logs is in the five 9s.  If you really need a 100% a would suggest to not use Serilog or any logging solution and directly maintain the integration with CloudWatch to ensure your logs are where you want them to be.

**Comment by zsims** [comment]
Thanks for the detailed response, I understand the complexity this would add. Just this sink is somewhat of an outlier as many of the other sinks support durable logging.

Will have a look what we could do from the consumer side. Thanks for all the input and great library, much appreciated :)

**Comment by buzzware** [comment]
I'm using Serilog with good success in Xamarin mobile apps, and durability is a high requirement for mobile. I've already built a durable logger for Logentries using DurableHttpSink from Serilog.Sinks.Http with a custom IHttpClient, TextFormatter and BatchFormatter. The same approach would probably work here.
