### ISSUE TITLE
net45 depreciated?

### ISSUE THREAD

**Issue by rtkelly13** [Cimpress-MCP/serilog-sinks-awscloudwatch#88]
I wanted to see if the depreciation of the .net framework logging has been intentional?
The readme still states that this package does support net45 frameworks

This commit removed the framework from the csproj
https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/commit/93ed40f413aed2203e92941e9c31af899c238fc1

Happy to give re-adding net45 support a go, but I know I can be more of a burden to maintain even if I could get it working again!

**Comment by wparad** [comment]
The readme update miss was an oversight.  The reason it was removed, was because standard is supposed to work for .Net as well, so building both versions was not necessary.

There was definitely configuration and management burden to having both versions and would want to avoid trying to make it in light of that.

**Comment by rtkelly13** [comment]
Completely understandable looks like I need to upgrade to at least v4.6.1 in order to have compatibility.

Might be worth saying the .net standard version you target in the readme and point people to this page to find out if their platform is supported.
https://dotnet.microsoft.com/platform/dotnet-standard

Thank you for getting back to me on that one!
